# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 15:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Absent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('absent', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'Absent',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('rate', models.IntegerField()),
            ],
            options={
                'db_table': 'Client',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=100)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.Client')),
            ],
            options={
                'db_table': 'Comment',
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('menu', models.TextField(blank=True, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('price', models.TextField(blank=True, null=True)),
                ('date', models.CharField(blank=True, max_length=100, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.Client')),
            ],
            options={
                'db_table': 'Meal',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('user_name', models.CharField(max_length=1000)),
                ('register_date', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=255)),
                ('role', models.IntegerField()),
                ('last_login', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Person',
            },
        ),
        migrations.CreateModel(
            name='Roster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.Meal')),
            ],
            options={
                'db_table': 'Roster',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('rate', models.IntegerField(default=0, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.Person')),
            ],
            options={
                'db_table': 'Staff',
            },
        ),
        migrations.AddField(
            model_name='roster',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.Staff'),
        ),
        migrations.AddField(
            model_name='comment',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.Meal'),
        ),
        migrations.AddField(
            model_name='client',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.Person'),
        ),
        migrations.AddField(
            model_name='absent',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.Staff'),
        ),
    ]
