# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-03 03:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_staff_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='meal_comment',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.Client'),
        ),
    ]
