# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-23 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20160803_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='apply',
            field=models.IntegerField(blank=True, default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='staff',
            name='apply_message',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='restriction',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
